function writeRecipes() {
    var recipesRef = db.collection("recipes");

    recipesRef.add({
        idMeal: "52771",
        strMeal: "Spicy Arrabiata Penne",
        strCategory: "Vegetarian",
        strArea: "Italian",
        strInstructions: "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
        strMealThumb: "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
        strTags: "Pasta,Curry",
        strIngredient1: "penne rigate",
        strIngredient2: "olive oil",
        strIngredient3: "garlic",
        strIngredient4: "chopped tomatoes",
        strIngredient5: "red chilli flakes",
        strIngredient6: "italian seasoning",
        strIngredient7: "basil",
        strIngredient8: "Parmigiano-Reggiano",
        strIngredient9: "",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strIngredient16: "",
        strIngredient17: "",
        strIngredient18: "",
        strIngredient19: "",
        strIngredient20: "",
        strMeasure1: "1 pound",
        strMeasure2: "1/4 cup",
        strMeasure3: "3 cloves",
        strMeasure4: "1 tin",
        strMeasure5: "1/2 teaspoon",
        strMeasure6: "1/2 teaspoon",
        strMeasure7: "6 leaves",
        strMeasure8: "sprinkling",
        strMeasure9: "",
        strMeasure10: "",
        strMeasure11: "",
        strMeasure12: "",
        strMeasure13: "",
        strMeasure14: "",
        strMeasure15: "",
        strMeasure16: "",
        strMeasure17: "",
        strMeasure18: "",
        strMeasure19: "",
        strMeasure20: "",
        last_updated: firebase.firestore.FieldValue.serverTimestamp()
    })
    recipesRef.add({
        idMeal: "52768",
        strMeal: "Apple Frangipan Tart",
        strCategory: "Dessert",
        strArea: "British",
        strInstructions: "Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.",
        strMealThumb: "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
        strTags: "Tart,Baking,Fruity",
        strIngredient1: "digestive biscuits",
        strIngredient2: "butter",
        strIngredient3: "Bramley apples",
        strIngredient4: "butter, softened",
        strIngredient5: "caster sugar",
        strIngredient6: "free-range eggs, beaten",
        strIngredient7: "ground almonds",
        strIngredient8: "almond extract",
        strIngredient9: "flaked almonds",
        strIngredient10: "",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strIngredient16: "",
        strIngredient17: "",
        strIngredient18: "",
        strIngredient19: "",
        strIngredient20: "",
        strMeasure1: "175g/6oz",
        strMeasure2: "75g/3oz",
        strMeasure3: "200g/7oz",
        strMeasure4: "75g/3oz",
        strMeasure5: "75g/3oz",
        strMeasure6: "2",
        strMeasure7: "75g/3oz",
        strMeasure8: "1 tsp",
        strMeasure9: "50g/1¾oz",
        strMeasure10: "",
        strMeasure11: "",
        strMeasure12: "",
        strMeasure13: "",
        strMeasure14: "",
        strMeasure15: "",
        strMeasure16: "",
        strMeasure17: "",
        strMeasure18: "",
        strMeasure19: "",
        strMeasure20: "",
        last_updated: firebase.firestore.FieldValue.serverTimestamp()
    })
    recipesRef.add({
        idMeal: "52767",
        strMeal: "Bakewell tart",
        strCategory: "Dessert",
        strArea: "British",
        strInstructions: "To make the pastry, measure the flour into a bowl and rub in the butter with your fingertips until the mixture resembles fine breadcrumbs. Add the water, mixing to form a soft dough.\r\nRoll out the dough on a lightly floured work surface and use to line a 20cm/8in flan tin. Leave in the fridge to chill for 30 minutes.\r\nPreheat the oven to 200C/400F/Gas 6 (180C fan).\r\nLine the pastry case with foil and fill with baking beans. Bake blind for about 15 minutes, then remove the beans and foil and cook for a further five minutes to dry out the base.\r\nFor the filing, spread the base of the flan generously with raspberry jam.\r\nMelt the butter in a pan, take off the heat and then stir in the sugar. Add ground almonds, egg and almond extract. Pour into the flan tin and sprinkle over the flaked almonds.\r\nBake for about 35 minutes. If the almonds seem to be browning too quickly, cover the tart loosely with foil to prevent them burning.",
        strMealThumb: "https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg",
        strTags: "Tart,Baking,Alcoholic",
        strIngredient1: "plain flour",
        strIngredient2: "chilled butter",
        strIngredient3: "cold water",
        strIngredient4: "raspberry jam",
        strIngredient5: "butter",
        strIngredient6: "caster sugar",
        strIngredient7: "ground almonds",
        strIngredient8: "free-range egg, beaten",
        strIngredient9: "almond extract",
        strIngredient10: "flaked almonds",
        strIngredient11: "",
        strIngredient12: "",
        strIngredient13: "",
        strIngredient14: "",
        strIngredient15: "",
        strIngredient16: "",
        strIngredient17: "",
        strIngredient18: "",
        strIngredient19: "",
        strIngredient20: "",
        strMeasure1: "175g/6oz",
        strMeasure2: "75g/2½oz",
        strMeasure3: "2-3 tbsp",
        strMeasure4: "1 tbsp",
        strMeasure5: "125g/4½oz",
        strMeasure6: "125g/4½oz",
        strMeasure7: "125g/4½oz",
        strMeasure8: "1",
        strMeasure9: "½ tsp",
        strMeasure10: "50g/1¾oz",
        strMeasure11: "",
        strMeasure12: "",
        strMeasure13: "",
        strMeasure14: "",
        strMeasure15: "",
        strMeasure16: "",
        strMeasure17: "",
        strMeasure18: "",
        strMeasure19: "",
        strMeasure20: "",
        last_updated: firebase.firestore.FieldValue.serverTimestamp()
    })
}